CREATE DATABASE pms;

CREATE TABLE products (
   id INT AUTO_INCREMENT PRIMARY KEY,
   sku VARCHAR(255) NOT NULL,
   name VARCHAR(255) NOT NULL,
   price DECIMAL(10, 2) NOT NULL,
   type VARCHAR(255) NOT NULL,
   attributes JSON,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);